<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cOSA" nsURI="http://www.example.org/cOSA" nsPrefix="cOSA">
  <eClassifiers xsi:type="ecore:EClass" name="Configuration" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" upperBound="-1"
        eType="#//Element" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iconfiguration" lowerBound="1"
        upperBound="-1" eType="#//InterfaceConfig" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biding" upperBound="-1"
        eType="#//Binding" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Connecteur" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceconnect" lowerBound="1"
        upperBound="-1" eType="#//InterfaceConnect" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="glue" lowerBound="1" eType="#//Glue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composant" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfacecompo" lowerBound="1"
        upperBound="-1" eType="#//InterfaceCompo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attachement" abstract="true" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceConfig" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceCompo" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceConnect" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Glue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedrole" lowerBound="1"
        upperBound="-1" eType="#//ProvidedRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredrole" lowerBound="1"
        upperBound="-1" eType="#//RequiredRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" abstract="true" eSuperTypes="#//InterfaceConnect"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedRole" eSuperTypes="#//Role"/>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredRole" eSuperTypes="#//Role"/>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true" eSuperTypes="#//InterfaceConfig #//InterfaceCompo"/>
  <eClassifiers xsi:type="ecore:EClass" name="Service" abstract="true" eSuperTypes="#//InterfaceCompo"/>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredPort" eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedPort" eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredService" eSuperTypes="#//Service"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedService" eSuperTypes="#//Service"/>
  <eClassifiers xsi:type="ecore:EClass" name="AComposantConnecteur" eSuperTypes="#//Attachement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedport" upperBound="-1"
        eType="#//ProvidedPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedservice" upperBound="-1"
        eType="#//ProvidedService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredrole" upperBound="-1"
        eType="#//RequiredRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AConnecteurComposant" eSuperTypes="#//Attachement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredport" upperBound="-1"
        eType="#//RequiredPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredservice" upperBound="-1"
        eType="#//RequiredService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedrole" upperBound="-1"
        eType="#//ProvidedRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedBinding" eSuperTypes="#//Binding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentPort" lowerBound="1"
        eType="#//ProvidedPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configPort" lowerBound="1"
        eType="#//ProvidedPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredBinding" eSuperTypes="#//Binding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configPort" lowerBound="1"
        eType="#//RequiredPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentPort" lowerBound="1"
        eType="#//RequiredPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binding" abstract="true"/>
</ecore:EPackage>
